[package]
name = "vvvst-dpf-rust"
version = "0.1.0"
edition = "2021"

[workspace]
members = ["xtask"]

[dependencies]
raw-window-handle = "0.6.2"
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
winit = "0.30.5"
wry = "0.45.0"

[lib]
crate-type = ["staticlib"]
